FROM ubuntu:20.04

MAINTAINER Kumar Gaurav

RUN apt update\
    && apt-get install -y python3-pip python3-dev \
    && apt install build-essential \
    && apt-get install manpages-dev \
    && cd /usr/local/bin \
    && DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata \
    && apt-get install -y pkg-config \
    && apt-get install -y  libxmlsec1-dev \
    && apt install unattended-upgrades -y


RUN apt update \
    && unattended-upgrade \
    && apt-get -qy autoremove \
    && python3 -m pip install psycopg2-binary==2.8.6

WORKDIR /root
RUN mkdir mutualCart
COPY . /root/mutualCart
WORKDIR /root/mutualCart/mutualCart/
EXPOSE 5001

RUN python3 -m pip install --no-cache-dir -r requirement.txt \
    && python3 manage.py collectstatic --noinput

CMD ["gunicorn", "mutualCart.wsgi:application", "--worker-class=gevent", "--worker-connections=1000", "--workers=2", "--timeout", "300000", "--graceful-timeout", "300000", "--keep-alive", "300000", "-b", "0.0.0.0:5001" ]
# CMD ["python3", "manage.py", "runserver",  "0.0.0.0:5001" ]
