# Generated by Django 3.2.4 on 2021-06-11 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('type', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.CharField(blank=True, max_length=2096, null=True)),
                ('filename', models.CharField(blank=True, max_length=256, null=True)),
                ('height', models.CharField(blank=True, max_length=256, null=True)),
                ('width', models.CharField(blank=True, max_length=256, null=True)),
                ('price', models.FloatField(default=0)),
                ('rating', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'mutual_product',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_count', models.IntegerField(default=0)),
                ('product_map', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_cart', to='Cart.product')),
            ],
            options={
                'db_table': 'mutual_cart',
            },
        ),
    ]
